In [4]:
import tensorflow as tf

A = tf.constant([
    [0,1],
    [1,2]
])

B = tf.constant([
    [5,6],
    [7,8]
])

print(A)
print(B)

tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [ ]:
##operations:

#Addition
c = tf.add(A, B)
print(c)

#subtraction
d = tf.subtract(B,A)
print(d)

#multiplication
e = tf.multiply(A, B)
print(e)

f = tf.divide(B, A)
print(f)


# -------------------------------------------------------------------------------------


tf.Tensor(
[[ 5  7]
 [ 8 10]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 5]
 [6 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0  6]
 [ 7 16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[inf  6.]
 [ 7.  4.]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[ 7  8]
 [19 22]], shape=(2, 2), dtype=int32)


In [ ]:
#matrix multplication

p = tf.matmul(A, B)
print(p)



##reshape tensor
X = tf.constant([[1,2,3,4,5,6]])

y = tf.reshape(X, (2,3))
print(y)

##Transpose matrix (rows become column and vice versa)
z = tf.constant([
    [2,3],
    [4,5]
])
print(tf.transpose(z))

tf.Tensor(
[[ 7  8]
 [19 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 4]
 [3 5]], shape=(2, 2), dtype=int32)


In [12]:
#square the tensor

sq = tf.constant([[1,2,3,4,5,5]])
# print(tf.square(sq))

sqr = tf.constant([[1,2,3,4,5,5]], dtype=tf.float32)
# print(tf.sqrt(sqr))


#Reduce sum (calculate sum )

print(tf.reduce_sum(sq))

print(tf.reduce_mean(sq))
print(tf.reduce_min(sq))
print(tf.reduce_max(sq))

tf.Tensor(20, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
